# Generated by Django 4.1.3 on 2023-08-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CD_API', '0002_cropdiseaseapi_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdiseaseapi',
            name='crop',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
