# Generated by Django 4.1.3 on 2023-08-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CD_API', '0003_alter_cropdiseaseapi_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
